name: Check if a package is already published
description: Check if a package is already published given its name and version
inputs:
  name:
    description: Name of the package
    required: true
  registry-url:
    description: URL of the registry
  token:
    description: Registry auth token
  version:
    description: Version of the package
    required: true
outputs:
  published:
    value: ${{ steps.result.outputs.published == 'true' }}
runs:
  using: composite
  steps:
    - env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      id: check-publish-status
      run: npm view --json ${{ inputs.registry-url && format('--registry={0}', inputs.registry-url) }} ${{ inputs.name }}@${{ inputs.version }} 2>/dev/null | tee /tmp/output.json || true
      shell: bash
    - id: result
      run: echo published=$(cat /tmp/output.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end') | tee --append $GITHUB_OUTPUT
      shell: bash
